Added use case to get user details from authentication
idx-academy/mic-orders pull request #102
Opened 2024-06-28 14:52 UTC by DenysLiubchenko

## Ticket
[#101](https://github.com/idx-academy/mic-orders/issues/101)
## Changes
Added new usecase to retrive user details from authentication and adding those parameters in JWT token.

2024-06-29 10:05 UTC, urio999 approved these changes, later dismissed

2024-06-29 15:54 UTC, ryhaldenys requested changes
Instead of moving SecurityUser from the boot module to the domain, create an interface, implement it in the SecurityUser class and after that, cast Principle to that interface.

2024-06-29 16:17 UTC, ryhaldenys submitted a review, later dismissed

2024-07-02 11:43 UTC, ryhaldenys approved these changes

2024-07-02 11:44 UTC, merged