Feature/224/State transition logic for sequential Order status changes
idx-academy/mic-orders pull request #225
Opened 2024-07-27 22:13 UTC by ABbondar

## Issues
#219 
## Summary of changes🔥
- implemented a state transition logic for sequential Order status changes.
- Implemented tests to cover all new lines of code.

2024-07-29 13:21 UTC, DenysLiubchenko requested changes

2024-07-29 13:21 UTC, DenysLiubchenko commented on code/orders-application/src/main/java/com/academy/orders/application/order/usecase/UpdateOrderStatusUseCaseImpl.java
> +		if (ROLE_ADMIN.equalsIgnoreCase(String.valueOf(role))) {
All security and permission logic must be only on api layer

2024-07-29 13:24 UTC, DenysLiubchenko submitted a review, later dismissed

2024-07-30 07:36 UTC, urio999 submitted a review, later dismissed

2024-07-30 13:04 UTC, ryhaldenys submitted a review, later dismissed

2024-07-31 08:40 UTC, ryhaldenys approved these changes

2024-07-31 08:45 UTC, urio999 approved these changes

2024-07-31 10:18 UTC, merged